bssa/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('', include('website.urls')),
    path('admin/', admin.site.urls),
]

website/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'website'

urlpatterns = [
    path(r'', views.home, name='home'),
    path(r'^results/$', views.results, name='results'),
    path(r'^learntoswim/$', views.learntoswim, name='learntoswim'),
    path(r'^contact/$', views.contact, name='contact'),
    path(r'^news/$', views.news, name='news'),
    path(r'^services/$', views.services, name='services'),
    path(r'^findclub/$', views.findclub, name='findclub'),
    path(r'^history/$', views.history, name='history'),
    path(r'^committee/$', views.committee, name='committee'),
    path(r'^gallery/$', views.gallery, name='gallery'),
    path(r'^categories/$', views.categories, name='categories'),
    path(r'^events/$', views.events, name='events'),
    path(r'^video/$', views.video, name='video'),
    path(r'^calendar/$', views.CalendarView.as_view(), name='calendar'),
]

website/models.py
from django.conf import settings
from django.db import models

# Create your models here.

class Event(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()

website/views.py
from django.http import HttpResponse
from django.shortcuts import render
from datetime import datetime
from django.shortcuts import render
from django.http import HttpResponse
from django.views import generic
from django.utils.safestring import mark_safe
from datetime import timedelta

from .models import *
from .utils import Calendar


def home(request):
    return render(request, 'website/home.html',)

def results(request):
    return render(request, 'website/results.html')

def learntoswim(request):
    return render(request, 'website/learntoswim.html')

def contact(request):
    return render(request, 'website/contact.html')   

def news(request):
    return render(request, 'website/news.html')   

def services(request):
    return render(request, 'website/services.html') 

def findclub(request):
    return render(request, 'website/findclub.html') 

def history(request):
    return render(request, 'website/history.html') 

def committee(request):
    return render(request, 'website/committee.html')

def gallery(request):
    return render(request, 'website/gallery.html')

def categories(request):
    return render(request, 'website/categories.html')

def events(request):
    return render(request, 'website/events.html')

def video(request):
    return render(request, 'website/video.html')

class CalendarView(generic.ListView):
    model = Event
    template_name = 'website/calendar.html'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # use today's date for the calendar
        d = get_date(self.request.GET.get('day', None))
        

      

        # Instantiate our calendar class with today's year and date
        cal = Calendar(d.year, d.month)

        # Call the formatmonth method, which returns our calendar as a table
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)
        return context

def get_date(req_day):
    if req_day:
        year, month = (int(x) for x in req_day.split('-'))
        return date(year, month, day=1)
    return datetime.today()

website/templates/website/Untitled-1.html
		
          <section >
				   <div id = "aff">
					   	  <center><h2><strong>AFFILIATIONS</strong></h2></center>
					<div class="row">	
						  
						
							  <div class="column">
								
								<img src="{% static "website/fina.png" %}" alt="fina" >
							  </div>
							  <div class="column">
								
								<img src="{% static "website/bnsc.png" %}"  alt="bnsc" >
							  </div>
							  <div class="column">
							   
								<img src="{% static "website/bnoc.png" %}" alt="bnoc" >
							</div>
							<div class="column">
								
								<img src="{% static "website/wasbo.png" %}" alt="wasbo">
							</div>
							<div class="column">
								
								<img src="{% static "website/cana.jpg" %}" alt="cana">
							</div>
							
							</div>
				   </div>
        </section> 
        <!-- Footer -->
				<div id="footer">
					<div class="container">
						<div class="row">
							<section class="col-3 col-6-narrower col-12-mobilep">
								<h3>Useful links</h3>
								<ul class="links">
									<li><a href="#">Upcoming Events</a></li>
									<li><a href="#">News</a></li>
									<li><a href="{% url 'website:findclub' %}">Swimming Clubs in Botswana</a></li>
									<li><a href="https://canaswim.com/">Confederation Africaine de Natation (C.A.N.A) Constitution</a></li>
								</ul>
							</section>
							<section class="col-3 col-6-narrower col-12-mobilep">
								<h3>Contact</h3>
								<h6>Address:</h6>
								<p>P O Box 163</p>
								<p>Gaborone</p>
								<h6>Telephone/Fax:</h6>
								<p>+267 71631166/+267 3904193</p>
								<p></p>
								<h6>Email:</h6>
								<p><a href="mailto:someone@example.com">botswanaswimming@gmail.com</a></p>
							</section>
							<section class="col-6 col-12-narrower">
								<h3>Get In Touch</h3>
								<form>
									<div class="row gtr-50">
										<div class="col-6 col-12-mobilep">
											<input type="text" name="name" id="name" placeholder="Name" />
										</div>
										<div class="col-6 col-12-mobilep">
											<input type="email" name="email" id="email" placeholder="Email" />
										</div>
										<div class="col-12">
											<textarea name="message" id="message" placeholder="Message" rows="5"></textarea>
										</div>
										<div class="col-12">
											<ul class="actions">
												<li><input type="submit" class="button alt" value="Send Message" /></li>
											</ul>
										</div>
									</div>
								</form>
							</section>
						</div>
					</div>

					<!-- Icons -->
						<ul class="icons">
								<a href="https://www.facebook.com/Botswana-Swimming-Sports-Association-314724768664061/?epa=SEARCH_BOX" class="fa fa-facebook"></a>
								<a href="#" class="fa fa-twitter"></a>
								<a href="https://www.instagram.com/botswana_swimming/" class="fa fa-instagram"></a>
								<a href="#" class="fa fa-youtube"></a>
						</ul>

					<!-- Copyright -->
						<div class="copyright">
							<ul class="menu">
									<p>© Botswana Swimming Sports Association</p>
							</ul>
						</div>

				</div>

		</div>

website/templates/website/base.html
{% load static %}
{% load sass_tags %}
<!DOCTYPE HTML>

<html>
	<head>
		<title>Arcana by HTML5 UP</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href={% static 'css/main.css' %}/>
		<link rel="stylesheet" href={% static 'css/simplefooter.css' %}/>
		<link href={% static 'sass/main.scss' %} rel="stylesheet" type="text/css" />
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
		
		<!--<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
		<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">-->
	<link rel="stylesheet" href={% static 'css/footer.css' %}>

	<style>
	
	</style>
	</head>
	<body class="is-preload">
			
		<div id="page-wrapper">
	  
			<!-- Header -->
			 <div class = "transparent">
				<div id="header">
                
					<!-- Logo -->
					<div class = "diamond">
						<div class = "dia">
			 <div class = logot>
							<a href="{% url 'website:home' %}" ><img src= "{% static "website/gal6.jpg" %}" height= "100px";
								width= "150px"; alt="bssa logo" id="logo"></a>
							</div>
						</div>
					</div>
					<div class="iconss">
						  
							<header class="ico" >
								
								<a href="https://www.facebook.com/Botswana-Swimming-Sports-Association-314724768664061/?epa=SEARCH_BOX" class="fa fa-facebook"></a>
								<a href="#" class="fa fa-twitter"></a>
								<a href="https://www.instagram.com/botswana_swimming/" class="fa fa-instagram"></a>
							
							</header>
						</div>
					<!-- Nav -->
						<nav id="nav">
							
							<ul>
								<li class="current"><a href="{% url 'website:home' %}">Home</a></li>
								<li>
									<a href="#">About BSSA</a>
									<ul>
										<li><a href="{% url 'website:history' %}">History</a></li>
										<li><a href="{% url 'website:committee' %}">Committiee</a></li>
										<li><a href="{% url 'website:gallery' %}">Gallery</a></li>
									</ul>
								</li>
								<li><a href="#">Disciplines</a>
									<ul>
											<li><a href="{% url 'website:categories' %}">Swimming Categories</a></li>
									</ul>
								</li>
								<li><a href="{% url 'website:events' %}">Events</a></li>
								<li><a href="{% url 'website:results' %}">Results</a></li>
								<li><a href="{% url 'website:learntoswim' %}">Learn to Swim</a></li>
								<li><a href="{% url 'website:news' %}">News</a></li>
								<li><a href="#">Membership</a>
									<ul>
											<li><a href="{% url 'website:services' %}">Membership Services</a></li>
											<li><a href="{% url 'website:findclub' %}">Find a club</a></li>
									</ul>
								</li>
								<li><a href="{% url 'website:contact' %}">Contact Us</a></li>
							</ul>
						</nav>

				</div>
				</div>
			<br>	<br>	<br>
			<br>	<br>	<br>
			<br>	<br>	<br>
			<br>	
		
           <!-- Banner -->
              <section id="banner">
	             <header>
		           <h2>Botswana Swimming Sport Association: <em> is the national governing body for the sport of swimming in Botswana</em></h2>
		           <a href="{% url 'website:history' %}" class="button">Learn More</a>
	             </header>
              </section>
				<br>
				
              {% block content %}
              {% endblock %}

	
		
		<br>
		<br>
		<br>
		<br>
	 <div id = footer>
		<div class="row1">
			<!---
		<center><h3><strong>AFFILIATIONS</strong></h3></center>
		
		<div class="column">
								
			<img src="{% static "website/fina.png" %}" alt="fina" >
		  </div>
		  <div class="column">
			
			<img src="{% static "website/bnsc.png" %}"  alt="bnsc" >
		  </div>
		  <div class="column">
		   
			<img src="{% static "website/bnoc.png" %}" alt="bnoc" >
		</div>
		
		<div class="column">
			
			<img src="{% static "website/cana.jpg" %}" alt="cana">
		</div>-->
		
		
				<footer id ="foot">
					<div class="container">
							<div class="inner-container">
								<h2 class="text-uppercase">Quick Links</h2>
					
							<ul class="list">
							  <li>
								<a href="#!">About Us</a>
							  </li>
							  <li>
								<a href="#!">BSSA Executive Committee</a>
							  </li>
							  <li>
								<a href="#!">BSSA National Selection Gala</a>
							  </li>
							  <li>
								<a href="#!">Events</a>
							  </li>
							</ul>
				<!--
					<div id = "contact">
									<h3>Contact</h3>
									<h6>Address:</h6>
									<p>P O Box 163</p>
									<p>Gaborone</p>
									<h6>Telephone/Fax:</h6>
									<p>+267 71631166/+267 3904193</p>
									<p></p>
									<h6>Email:</h6>
									<p><a href="mailto:someone@example.com">botswanaswimming@gmail.com</a></p>
												
					</div>		-->
					<div class="social">
						<a href="https://www.facebook.com/Botswana-Swimming-Sports-Association-314724768664061/?epa=SEARCH_BOX" class="fa fa-facebook"></a>
						<a href="#" class="fa fa-twitter"></a>
						<a href="https://www.instagram.com/botswana_swimming/" class="fa fa-instagram"></a>
					</div>
					<div class="footer-copyright">
								<p>© Botswana Swimming Sports Association</p>
							</div>
						</div>
					</div>
					</footer>
		</div>
		<!-- Scripts -->

        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/jquery.dropotron.min.js' %}"></script>
        <script src="{% static 'js/browser.min.js' %}"></script>
        <script src="{% static 'js/breakpoints.min.js' %}"></script>
        <script src="{% static 'js/util.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>

	</body>
</html>

website/templates/website/base2.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
  <link rel="stylesheet" type="text/css" href={% static 'css/cal.css' %}>

  <title>Django Calendar App</title>
</head>
<body>

  {% block content %}
  {% endblock %}

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS 
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>-->

  {% block script %}
  {% endblock %}
</body>
</html>

website/templates/website/events.html
{% extends 'website/base.html' %}

{% load static %}

{% block content %}

<!-- Events Calendar -->
<p>Click the link below to view the calendar</p>
<br>
<a class="button" href="{% url 'website:calendar' %}">Calendar Events</a></li>



{% endblock %}

website/templates/website/findclub.html
{% extends 'website/base.html' %}

{% load static %}

{% block content %}

<!-- Club Table -->
<table>  
    <tr>  
        <th>Club Name/Aquatic Centre</th>
        <th>Location</th>
        <th>Contact</th>
        <th>Email</th>
        <th>Website Link</th>
    </tr>  
    <tr>  
        <td>Darrel Morton's School of Swimming</td>
        <td>75791 Setlhoa Village, Gaborone, Botswana </td>
        <td>+267 3973383/+267 71619388</td>
        <td><a href="mailto:someone@example.com">info@dmss.co.bw</a></td>
        <td><a href="http://www.dmss.co.bw/" >Visit Site</a></td>
    </tr>  
    <tr>  
        <td>University of Botswana Swimming Club</td>
        <td>UB Gaborone, Botswana </td>
        <td>+267 000000</td>
        <td><a href="mailto:someone@example.com">email</a></td>
        <td><a href="https://www.facebook.com/UBSwimClub/" >Visit facebook Page</a></td>
    </tr>   
    <tr>  
        <td>UB Aquatic Centre</td>
        <td>UB, Gaborone, Botswana </td>
        <td>+267 355 5209</td>
        <td><a href="mailto:someone@example.com">email</a></td>
        <td><a href="https://www.ub.bw/campus-life/culture-sports-and-recreation/facilities/ub-aquatic-centre" >Visit Site</a></td>
    </tr>  
    <tr>  
        <td>Gaborone Aquatic Centre(Waterbabies)</td>
        <td>Kgale, Gaborone, Botswana </td>
        <td>+267 393 9883</td>
        <td><a href="mailto:someone@example.com">craig@waterbabiesbw.com</a></td>
        <td><a href="http://www.waterbabiesbw.com/" >Visit Site</a></td>
    </tr>  
    </table>  



{% endblock %}

website/templates/website/gallery.html
{% extends 'website/base.html' %}

{% load static %}

{% block content %}
  
     <style>
         body {
  background-color: #eee;
}
.hello {
  opacity: 1 !important;
}
.full {
  position: fixed;
  left: 0;
  top: 0;
  width: 100%;
  height: 100%;
  z-index: 1;
}
.full .content {
  background-color: rgba(0,0,0,0.75) !important;
  height: 100%;
  width: 100%;
  display: grid;
}
.full .content img {
  left: 50%;
  transform: translate3d(0, 0, 0);
  animation: zoomin 1s ease;
  max-width: 100%;
  max-height: 100%;
  margin: auto;
}
.byebye {
  opacity: 0;
}
.byebye:hover {
  transform: scale(0.2) !important;
}
.gallery {
  display: grid;
  grid-column-gap: 8px;
  grid-row-gap: 8px;
  grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
  grid-auto-rows: 8px;
}
.gallery img {
  max-width: 100%;
  border-radius: 8px;
  box-shadow: 0 0 16px #333;
  transition: all 1.5s ease;
}
.gallery img:hover {
  box-shadow: 0 0 32px #333;
}
.gallery .content {
  padding: 4px;
}
.gallery .gallery-item {
  transition: grid-row-start 300ms linear;
  transition: transform 300ms ease;
  transition: all 0.5s ease;
  cursor: pointer;
}
.gallery .gallery-item:hover {
  transform: scale(1.025);
}
@media (max-width: 600px) {
  .gallery {
    grid-template-columns: repeat(auto-fill, minmax(30%, 1fr));
  }
}
@media (max-width: 400px) {
  .gallery {
    grid-template-columns: repeat(auto-fill, minmax(50%, 1fr));
  }
}
@-moz-keyframes zoomin {
  0% {
    max-width: 50%;
    transform: rotate(-30deg);
    filter: blur(4px);
  }
  30% {
    filter: blur(4px);
    transform: rotate(-80deg);
  }
  70% {
    max-width: 50%;
    transform: rotate(45deg);
  }
  100% {
    max-width: 100%;
    transform: rotate(0deg);
  }
}
@-webkit-keyframes zoomin {
  0% {
    max-width: 50%;
    transform: rotate(-30deg);
    filter: blur(4px);
  }
  30% {
    filter: blur(4px);
    transform: rotate(-80deg);
  }
  70% {
    max-width: 50%;
    transform: rotate(45deg);
  }
  100% {
    max-width: 100%;
    transform: rotate(0deg);
  }
}
@-o-keyframes zoomin {
  0% {
    max-width: 50%;
    transform: rotate(-30deg);
    filter: blur(4px);
  }
  30% {
    filter: blur(4px);
    transform: rotate(-80deg);
  }
  70% {
    max-width: 50%;
    transform: rotate(45deg);
  }
  100% {
    max-width: 100%;
    transform: rotate(0deg);
  }
}
@keyframes zoomin {
  0% {
    max-width: 50%;
    transform: rotate(-30deg);
    filter: blur(4px);
  }
  30% {
    filter: blur(4px);
    transform: rotate(-80deg);
  }
  70% {
    max-width: 50%;
    transform: rotate(45deg);
  }
  100% {
    max-width: 100%;
    transform: rotate(0deg);
  }
}

</style>
  <body>
    <h1>BSSA Gallery</h1>

    <div class="gallery" id="gallery">
        <div class="gallery-item">
            <div class="content"><img src="{% static "website/gal1.jpg" %}" alt=""></div>
        </div>
        <div class="gallery-item">
            <div class="content"><img src="{% static "website/gal2.jpg" %}" alt=""></div>
        </div>
        <div class="gallery-item">
            <div class="content"><img src="{% static "website/gal3.jpg" %}" alt=""></div>
        </div>
        <div class="gallery-item">
            <div class="content"><img src="{% static "website/gal4.jpg" %}" alt=""></div>
        </div>
        <div class="gallery-item">
            <div class="content"><img src="{% static "website/gal5.jpg" %}" alt=""></div>
        </div>
        <div class="gallery-item">
            <div class="content"><img src="{% static "website/gal6.jpeg" %}" alt=""></div>
        </div>
        <div class="gallery-item">
            <div class="content"><img src="{% static "website/gal7.jpg" %}" alt=""></div>
        </div>
        <div class="gallery-item">
            <div class="content"><img src="{% static "website/gal8.jpg" %}" alt=""></div>
        </div>
        <div class="gallery-item">
            <div class="content"><img src="{% static "website/gal9.jpg" %}" alt=""></div>
        </div>
        <div class="gallery-item">
            <div class="content"><img src="{% static "website/gal10.jpg" %}" alt=""></div>
        </div>
        <div class="gallery-item">
            <div class="content"><img src="{% static "website/gal11.jpg" %}" alt=""></div>
        </div>
        <div class="gallery-item">
            <div class="content"><img src="{% static "website/gal12.jpg" %}" alt=""></div>
        </div>
        <div class="gallery-item">
            <div class="content"><img src="{% static "website/gal13.jpg" %}" alt=""></div>
        </div>
        <div class="gallery-item">
            <div class="content"><img src="{% static "website/gal14.gif" %}" alt=""></div>
        </div>
        <div class="gallery-item">
            <div class="content"><img src="{% static "website/gal14.jpg" %}" alt=""></div>
        </div>
        <div class="gallery-item">
            <div class="content"><img src="{% static "website/gal15.png" %}" alt=""></div>
        </div>
        <div class="gallery-item">
            <div class="content"><img src="{% static "website/gal16.jpg" %}" alt=""></div>
        </div>
        <div class="gallery-item">
            <div class="content"><img src="{% static "website/gal18.jpg" %}" alt=""></div>
        </div>
        <div class="gallery-item">
            <div class="content"><img src="{% static "website/gal19.jpeg" %}" alt=""></div>
        </div>
        <div class="gallery-item">
            <div class="content"><img src="{% static "website/gal20.jpg" %}" alt=""></div>
        </div>
        <div class="gallery-item">
            <div class="content"><img src="{% static "website/gal21.jpg" %}" alt=""></div>
        </div>
        <div class="gallery-item">
            <div class="content"><img src="{% static "website/gal22.jpg" %}" alt=""></div>
        </div>
        <div class="gallery-item">
            <div class="content"><img src="{% static "website/news3.jpg" %}" alt=""></div>
        </div>
        <div class="gallery-item">
            <div class="content"><img src="{% static "website/gal10.jpg" %}" alt=""></div>
        </div>
        <div class="gallery-item">
            <div class="content"><img src="{% static "website/face5.jpe g" %}" alt=""></div>
        </div>
    </div>
</body>
<script>
    var gallery = document.querySelector('#gallery');
var getVal = function (elem, style) { return parseInt(window.getComputedStyle(elem).getPropertyValue(style)); };
var getHeight = function (item) { return item.querySelector('.content').getBoundingClientRect().height; };
var resizeAll = function () {
    var altura = getVal(gallery, 'grid-auto-rows');
    var gap = getVal(gallery, 'grid-row-gap');
    gallery.querySelectorAll('.gallery-item').forEach(function (item) {
        var el = item;
        el.style.gridRowEnd = "span " + Math.ceil((getHeight(item) + gap) / (altura + gap));
    });
};
gallery.querySelectorAll('img').forEach(function (item) {
    item.classList.add('byebye');
    if (item.complete) {
        console.log(item.src);
    }
    else {
        item.addEventListener('load', function () {
            var altura = getVal(gallery, 'grid-auto-rows');
            var gap = getVal(gallery, 'grid-row-gap');
            var gitem = item.parentElement.parentElement;
            gitem.style.gridRowEnd = "span " + Math.ceil((getHeight(gitem) + gap) / (altura + gap));
            item.classList.remove('byebye');
        });
    }
});
window.addEventListener('resize', resizeAll);
gallery.querySelectorAll('.gallery-item').forEach(function (item) {
    item.addEventListener('click', function () {        
        item.classList.toggle('full');        
    });
});

</script>

{% endblock %}

website/templates/website/home.html
{% extends 'website/base.html' %}

{% load static %}

{% block content %}
       
			<!-- Highlights -->
			<div id="back">
				<section class="wrapper style1">
					<div class="container">
						<div class="row">
							<section class="col-6 col-12-narrower">
								<div class="box post">
									<h2>Recent News</h2>
									<a href="#" class="image left"><img src="{% static "website/news.jpg" %}" alt="" /></a>
									<div class="inner">
										<h3>All the best to our Swimmers going ! 🇧🇼</h3>
										<p>Duis neque nisi, dapibus sed mattis et quis, nibh. Sed et dapibus nisl amet mattis, sed a rutrum accumsan sed. Suspendisse eu.</p>
										<p>09/07/2019</p>
										<a href="#" class="button">Read More</a>
									</div>
								</div>
							</section>
							<section class="col-6 col-12-narrower">
								<div class="box post">
									<h2>Upcoming Events</h2>
									<a href="#" class="image left"><img src="{% static "website/news1.jpg" %}" alt="" /></a>
									<div class="inner">
										<h3>The 18th FINA World Championships Gwangju 2019  Jul. 12-28, 2019</h3>
										<p>Duis neque nisi, dapibus sed mattis et quis, nibh. Sed et dapibus nisl amet mattis, sed a rutrum accumsan sed. Suspendisse eu.</p>
										<p>25/10/2019</p>
										<a href="#" class="button">Read More</a> <br><br>
										<a href="#" class="button">More Events</a>
									</div>
								</div>
							</section>
						</div>
						<div class="row">
							<section class="col-6 col-12-narrower">
								<div class="box post">
									<a href="#" class="image left"><img src="{% static "website/news1.jpg" %}" alt="" /></a>
									<div class="inner">
										<h3>Check out the CANA Swim Website for up to date information. Botswana falls under Zone 4</h3>
										<p>Duis neque nisi, dapibus sed mattis et quis, nibh. Sed et dapibus nisl amet mattis, sed a rutrum accumsan sed. Suspendisse eu.</p>
										<p>08/07/2019</p>		
										<a href="#" class="button">Read More</a>
									</div>
								</div>
							</section>
							<section class="col-6 col-12-narrower">
									<div class="box post">
											<h2>Recent Video Highlights</h2>
											<video width="320" height="240" controls>
													<source src="{% static "website/swim8.mp4" %}" type="video/mp4">
													<source src="movie.ogg" type="video/ogg">
													Your browser does not support the video tag.
												
											</video>
											
									</div>
							</section>
						
						</div>
					</div>
				</section>
			</div>
			<!-- Gigantic Heading -->
		<!-- <section id="cta" class="wrapper style3">
					<div class="container">
						<header>
							<h2>Are you ready to continue your quest?</h2>
							<a href="#" class="button">Insert Coin</a>
						</header>
					</div>
				</section>-->


			<!-- search bar-->
			
			
									<!-- Search bar-->
								    <div id= sea>
									<div class="s01" >
											<form>
										       
											  <fieldset>
												<center><h2>Find Pool or Club near you!</h2></center>
											  </fieldset>
											  <div class="inner-form">
												<div class="input-field second-wrap">
												 <center> <input id="location" type="text" placeholder="location" /></center>

												</div><br><br>
												<div class="input-field third-wrap">
												  <center><button class="btn-search" type="button">Search</button></center>
												</div>
											  </div>
											 
											</form>
										 </div>
								    </div>
			<!-- CTA -->
		
			
		
	         
 
{% endblock %}